### ISSUE TITLE
Once port is set to reverse (input) unable to set back to forward (output)

### ISSUE THREAD

**Issue by humblewizard** [jmendeth/parport.js#4]
Upon startup the output port is working properly as an output. After setting the control register C5 to reverse then data can be read successfully on the port:

```
     port.writeControl(32);   // set C5
     var data = port.readData(); 
```

Now is the trouble:

```
     port.writeControl(0);   // clear C5
     port.writeData(255);
```

This does nothing. I can see from monitoring the external pins that the port is still in reverse mode/ tristated. 

When I stop the process and restart then the port comes up in forward (output) direction until the C5 is set again.

**Comment by mildsunrise** [comment]
Unfortunately I don't think I can be of help here. As I said earlier this addon does not do any interfacing with the OS, it relies on Parallell-Port to get the job done. Thus, any issues like this should be reported there.

It's a long way since I last used this, but I remember switching directions without problems. The issue could be platform-specific. Which OS are you running?

**Comment by humblewizard** [comment]
The node-lpt formerly had this same issue. Because Denis no longer had a parallel port to play with he sent me some c files to experiment with and as a result he found the problem. His tool node-lpt no longer has this issue. 

I have the problem with parport.js using two different Ubuntu platforms having parallel cards from different manufacturers.

**Comment by mildsunrise** [comment]
The author seems unresponsive. Because I'm not able to maintain my own parallell interfacing library, I'm deprecating this.
